### ISSUE TITLE
Demo not running

### ISSUE THREAD

**Issue by AnikaP** [davidjesusacu/polyrnn-pp#26]
Hey! 

I'm trying to run the demo, which fails with:

```
./src/demo_inference.sh 
Traceback (most recent call last):
  File "src/inference.py", line 9, in <module>
    from EvalNet import EvalNet
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/src/EvalNet.py", line 1, in <module>
    import tensorflow.contrib.layers as layers
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 22, in <module>
    from tensorflow.contrib import bayesflow
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/bayesflow/__init__.py", line 24, in <module>
    from tensorflow.contrib.bayesflow.python.ops import csiszar_divergence
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/bayesflow/python/ops/csiszar_divergence.py", line 26, in <module>
    from tensorflow.contrib.bayesflow.python.ops.csiszar_divergence_impl import *
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/bayesflow/python/ops/csiszar_divergence_impl.py", line 42, in <module>
    from tensorflow.contrib import framework as contrib_framework
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/__init__.py", line 89, in <module>
    from tensorflow.contrib.framework.python.ops import *
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/__init__.py", line 24, in <module>
    from tensorflow.contrib.framework.python.ops.checkpoint_ops import *
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/checkpoint_ops.py", line 22, in <module>
    from tensorflow.contrib.framework.python.ops import gen_checkpoint_ops
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/gen_checkpoint_ops.py", line 248, in <module>
    _op_def_lib = _InitOpDefLibrary(b"\n\223\001\n\026GenerateVocabRemapping\022\022\n\016new_vocab_file\030\007\022\022\n\016old_vocab_file\030\007\032\r\n\tremapping\030\t\032\017\n\013num_present\030\003\"\031\n\020new_vocab_offset\022\003int(\001\"\026\n\rnum_new_vocab\022\003int(\001\n\335\001\n\022LoadAndRemapMatrix\022\r\n\tckpt_path\030\007\022\023\n\017old_tensor_name\030\007\022\021\n\rrow_remapping\030\t\022\021\n\rcol_remapping\030\t\022\027\n\023initializing_values\030\001\032\021\n\routput_matrix\030\001\"\021\n\010num_rows\022\003int(\001\"\023\n\010num_cols\022\003int(\0010\001\"&\n\022max_rows_in_memory\022\003int\032\013\030\377\377\377\377\377\377\377\377\377\001\210\001\001")
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/gen_checkpoint_ops.py", line 167, in _InitOpDefLibrary
    _op_def_registry.register_op_list(op_list)
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/tensorflow_core/python/framework/op_def_registry.py", line 38, in register_op_list
    % (op_def.name, _registered_ops[op_def.name], op_def))
ValueError: Registered op_def for GenerateVocabRemapping (name: "GenerateVocabRemapping"
input_arg {
  name: "new_vocab_file"
  type: DT_STRING
}
input_arg {
  name: "old_vocab_file"
  type: DT_STRING
}
output_arg {
  name: "remapping"
  type: DT_INT64
}
output_arg {
  name: "num_present"
  type: DT_INT32
}
attr {
  name: "new_vocab_offset"
  type: "int"
  has_minimum: true
}
attr {
  name: "num_new_vocab"
  type: "int"
  has_minimum: true
}
attr {
  name: "old_vocab_size"
  type: "int"
  default_value {
    i: -1
  }
  has_minimum: true
  minimum: -1
}
) not equal to op_def to register (name: "GenerateVocabRemapping"
input_arg {
  name: "new_vocab_file"
  type: DT_STRING
}
input_arg {
  name: "old_vocab_file"
  type: DT_STRING
}
output_arg {
  name: "remapping"
  type: DT_INT64
}
output_arg {
  name: "num_present"
  type: DT_INT32
}
attr {
  name: "new_vocab_offset"
  type: "int"
  has_minimum: true
}
attr {
  name: "num_new_vocab"
  type: "int"
  has_minimum: true
}
)
Traceback (most recent call last):
  File "src/vis_predictions.py", line 9, in <module>
    from poly_utils import vis_polys
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/src/poly_utils.py", line 5, in <module>
    import skimage.draw as draw
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/skimage/util/__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "/home/anika/Documents/workspace/markup_tools/polyrnn/env/local/lib/python2.7/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name _validate_lengths
```

What am I missing?

**Comment by shiveshc** [comment]
Did you find a solution? I am getting a similar error while trying to use matterport mask_RCNN.
I get this error only when I use tensorflow-gpu (2.0.0) and not when i use just tensorflow
