### ISSUE TITLE
Tensorflow CPU Mode - Value Error in Demo Inference

### ISSUE THREAD

**Issue by TillBeemelmanns** [davidjesusacu/polyrnn-pp#8]
When execute the demo script (`./src/demo_inference.s`) on tensorflow cpu mode, I have experienced the following error.

```
INFO:tensorflow:Building EvalNet...
2018-06-13 16:46:45.885704: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from models/evalnet/evalnet.ckpt
INFO:tensorflow:Building PolygonRNN++ ...
Traceback (most recent call last):
  File "src/inference.py", line 115, in <module>
    tf.app.run(inference)
  File "/home/beemelmanns/Dokumente/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "src/inference.py", line 69, in inference
    model = PolygonModel(FLAGS.PolyRNN_metagraph, polyGraph)
  File "/home/beemelmanns/Dokumente/polyrnn/src/PolygonModel.py", line 32, in __init__
    self._restore_graph(meta_graph_path)
  File "/home/beemelmanns/Dokumente/polyrnn/src/PolygonModel.py", line 36, in _restore_graph
    self.saver = tf.train.import_meta_graph(meta_graph_path, clear_devices=True)
  File "/home/beemelmanns/Dokumente/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1955, in import_meta_graph
    **kwargs)
  File "/home/beemelmanns/Dokumente/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 743, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/beemelmanns/Dokumente/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/beemelmanns/Dokumente/polyrnn/env/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 493, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs 'int32, int32, int32, int32' do not match 3 inputs specified; Op<name=GatherTree; signature=step_ids:T, parent_ids:T, max_sequence_lengths:int32, end_token:T -> beams:T; attr=T:type,allowed=[DT_INT32]>; NodeDef: GatherTree = GatherTree[T=DT_INT32, _output_shapes=[[?,1,8]]](TensorArrayStack_1/TensorArrayGatherV3, TensorArrayStack_2/TensorArrayGatherV3, Select_69)

0it [00:00, ?it/s]
```

**Comment by davidjesusacu** [comment]
Please check that you are using tf 1.3.
Also check issues 2 and 3

Thanks
